### ISSUE TITLE
TypeError with mqtt

### ISSUE THREAD

**Issue by optimismus** [danielfett/bluebattery.py#13]
Hi,
I tried to use bb_cli on a RPI3b+ with newest raspian. Installation works great, following the README.
The `bb_cli log` command worked, the RPI connects to my BB via ASUS BT500 and received data e.g. voltage.
But when I try to use mqtt to put those data into my "Home Assistant" I got a TypeError:
`pi@raspberrypi:~ $ bb_cli mqtt --host 192.168.1.1 --port 1883 --username muser --password geheim --topic service/bluebattery/live --client-id 666
Traceback (most recent call last):
  File "/usr/local/bin/bb_cli", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/dist-packages/bluebattery/cli.py", line 45, in run
    output = MQTTOutput(args)
  File "/usr/local/lib/python3.9/dist-packages/bluebattery/output/mqtt.py", line 45, in __init__
    self.client.connect(args.host, args.port)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 979, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'`

Because I am very new to mqtt, this my fault?! But I use mqtt for tasmota sucessfully.
Regards Axel

**Comment by Naaf3** [comment]
I have the exact same problem. bb_cli log is working but bb_cli mqtt with the credentials for the mqtt broker doesn't work and I get the same error as @optimismus 

The same settings for the mqtt broker work with another skript.

Any ideas?

Regards
Basti
